name: hnaskolab_001528_demo
channels:
    - conda-forge
dependencies:
    - python==3.13
    - ipykernel
    - matplotlib
    - dandi
    - networkx
    - pip
    - pip:
          - remfile
          - hnasko-lab-to-nwb @ git+https://github.com/catalystneuro/hnasko-lab-to-nwb.git@main
