name: clandinin_notebook_dandi
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - asttokens=2.4.1=pyhd8ed1ab_0
  - bzip2=1.0.8=hd590300_5
  - ca-certificates=2023.11.17=hbcca054_0
  - comm=0.1.4=pyhd8ed1ab_0
  - debugpy=1.8.0=py311hb755f60_1
  - decorator=5.1.1=pyhd8ed1ab_0
  - exceptiongroup=1.2.0=pyhd8ed1ab_0
  - executing=2.0.1=pyhd8ed1ab_0
  - importlib-metadata=7.0.0=pyha770c72_0
  - importlib_metadata=7.0.0=hd8ed1ab_0
  - ipykernel=6.26.0=pyhf8b6a83_0
  - ipython=8.18.1=pyh707e725_3
  - jedi=0.19.1=pyhd8ed1ab_0
  - jupyter_client=8.6.0=pyhd8ed1ab_0
  - jupyter_core=5.5.0=py311h38be061_0
  - ld_impl_linux-64=2.40=h41732ed_0
  - libexpat=2.5.0=hcb278e6_1
  - libffi=3.4.2=h7f98852_5
  - libgcc-ng=13.2.0=h807b86a_3
  - libgomp=13.2.0=h807b86a_3
  - libnsl=2.0.1=hd590300_0
  - libsodium=1.0.18=h36c2ea0_1
  - libsqlite=3.44.2=h2797004_0
  - libstdcxx-ng=13.2.0=h7e041cc_3
  - libuuid=2.38.1=h0b41bf4_0
  - libzlib=1.2.13=hd590300_5
  - matplotlib-inline=0.1.6=pyhd8ed1ab_0
  - ncurses=6.4=h59595ed_2
  - nest-asyncio=1.5.8=pyhd8ed1ab_0
  - openssl=3.2.0=hd590300_1
  - packaging=23.2=pyhd8ed1ab_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh1a96a4e_2
  - pickleshare=0.7.5=py_1003
  - pip=23.3.1=pyhd8ed1ab_0
  - platformdirs=4.1.0=pyhd8ed1ab_0
  - prompt-toolkit=3.0.41=pyha770c72_0
  - psutil=5.9.5=py311h459d7ec_1
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pure_eval=0.2.2=pyhd8ed1ab_0
  - pygments=2.17.2=pyhd8ed1ab_0
  - python=3.11.6=hab00c5b_0_cpython
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.11=4_cp311
  - pyzmq=25.1.2=py311h34ded2d_0
  - readline=8.2=h8228510_1
  - setuptools=68.2.2=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - stack_data=0.6.2=pyhd8ed1ab_0
  - tk=8.6.13=noxft_h4845f30_101
  - tornado=6.3.3=py311h459d7ec_1
  - traitlets=5.14.0=pyhd8ed1ab_0
  - typing_extensions=4.9.0=pyha770c72_0
  - wcwidth=0.2.12=pyhd8ed1ab_0
  - wheel=0.42.0=pyhd8ed1ab_0
  - xz=5.2.6=h166bdaf_0
  - zeromq=4.3.5=h59595ed_0
  - zipp=3.17.0=pyhd8ed1ab_0
  - pip:
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - appdirs==1.4.4
      - arrow==1.3.0
      - asciitree==0.3.3
      - attrs==23.1.0
      - bidsschematools==0.7.2
      - blessed==1.20.0
      - boto3==1.33.11
      - botocore==1.33.11
      - certifi==2023.11.17
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - ci-info==0.3.0
      - click==8.1.7
      - click-didyoumean==0.3.0
      - contourpy==1.2.0
      - cryptography==41.0.7
      - cycler==0.12.1
      - dandi==0.58.1
      - dandischema==0.8.4
      - dnspython==2.4.2
      - email-validator==2.1.0.post1
      - etelemetry==0.3.1
      - fasteners==0.19
      - fonttools==4.46.0
      - fqdn==1.5.1
      - frozenlist==1.4.0
      - fscacher==0.4.0
      - fsspec==2023.12.1
      - h5py==3.10.0
      - hdmf==3.11.0
      - humanize==4.9.0
      - idna==3.6
      - interleave==0.2.1
      - isodate==0.6.1
      - isoduration==20.11.0
      - jaraco-classes==3.3.0
      - jeepney==0.8.0
      - jmespath==1.0.1
      - joblib==1.3.2
      - jsonpointer==2.4
      - jsonschema==4.20.0
      - jsonschema-specifications==2023.11.2
      - keyring==24.3.0
      - keyrings-alt==5.0.0
      - kiwisolver==1.4.5
      - matplotlib==3.8.2
      - more-itertools==10.1.0
      - multidict==6.0.4
      - natsort==8.4.0
      - numcodecs==0.12.1
      - numpy==1.26.2
      - nwbinspector==0.4.31
      - pandas==2.1.4
      - pillow==10.1.0
      - pycparser==2.21
      - pycryptodomex==3.19.0
      - pydantic==1.10.13
      - pynwb==2.5.0
      - pyout==0.7.3
      - pyparsing==3.1.1
      - pytz==2023.3.post1
      - pyyaml==6.0.1
      - referencing==0.32.0
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3987==1.3.8
      - rpds-py==0.13.2
      - ruamel-yaml==0.18.5
      - ruamel-yaml-clib==0.2.8
      - s3fs==0.4.2
      - s3transfer==0.8.2
      - scipy==1.11.4
      - secretstorage==3.3.3
      - semantic-version==2.10.0
      - tenacity==8.2.3
      - tqdm==4.66.1
      - types-python-dateutil==2.8.19.14
      - tzdata==2023.3
      - uri-template==1.3.0
      - urllib3==2.0.7
      - webcolors==1.13
      - yarl==1.9.4
      - zarr==2.16.1
      - zarr-checksum==0.2.12
