name: kindlab_001457_demo
channels:
    - conda-forge
dependencies:
    - python==3.11
    - ipywidgets
    - pip
    - pip:
          - dandi
          - jupyter
          - matplotlib
          - pynwb
          - remfile
          - plotly
