# run: conda env create --file environment.yml
name: dan_notebook_env
channels:
    - conda-forge
dependencies:
    - python==3.13
    - ipykernel
    - matplotlib
    - networkx
    - pip
    - pip:
      - dandi
      - remfile
      - dan-lab-to-nwb @ git+https://github.com/catalystneuro/dan-lab-to-nwb.git@main