name: visual_coding_notebooks_created_on_2_19_2024
channels:
  - conda-forge
  - defaults
dependencies:
  - aom=3.8.1=h63175ca_0
  - bzip2=1.0.8=he774522_0
  - ca-certificates=2024.3.11=haa95532_0
  - cairo=1.18.0=h1fef639_0
  - dav1d=1.2.1=hcfcfb64_0
  - expat=2.5.0=h63175ca_1
  - ffmpeg=6.1.1=gpl_hb766fab_104
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_1
  - fontconfig=2.14.2=hbde0cde_0
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - freetype=2.12.1=hdaf720e_2
  - gettext=0.21.1=h5728263_0
  - git=2.40.1=haa95532_1
  - graphite2=1.3.13=1000
  - harfbuzz=8.3.0=h7ab893a_0
  - icu=73.2=h63175ca_0
  - libexpat=2.5.0=h63175ca_1
  - libffi=3.4.4=hd77b12b_0
  - libglib=2.78.4=h16e383f_0
  - libiconv=1.17=hcfcfb64_2
  - libopus=1.3.1=h8ffe710_1
  - libpng=1.6.43=h19919ed_0
  - libxml2=2.12.5=hc3477c8_0
  - libzlib=1.2.13=hcfcfb64_5
  - openh264=2.4.1=h63175ca_0
  - openssl=3.2.1=hcfcfb64_0
  - pcre2=10.42=h17e33f8_0
  - pip=23.3.1=py311haa95532_0
  - pixman=0.43.2=h63175ca_0
  - python=3.11.7=he1021f5_0
  - setuptools=68.2.2=py311haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - svt-av1=1.8.0=h63175ca_0
  - tk=8.6.12=h2bbff1b_0
  - ucrt=10.0.22621.0=h57928b3_0
  - vc=14.2=h21ff451_1
  - vc14_runtime=14.38.33130=h82b7239_18
  - vs2015_runtime=14.38.33130=hcb4865c_18
  - wheel=0.41.2=py311haa95532_0
  - x264=1!164.3095=h8ffe710_2
  - x265=3.5=h2d74725_3
  - xz=5.4.5=h8cc25b3_0
  - zlib=1.2.13=hcfcfb64_5
  - pip:
      - aiobotocore==2.12.0
      - aiohttp==3.9.3
      - aioitertools==0.11.0
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anyio==4.3.0
      - appdirs==1.4.4
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asciitree==0.3.3
      - asttokens==2.4.1
      - async-lru==2.0.4
      - attrs==23.2.0
      - babel==2.14.0
      - beautifulsoup4==4.12.3
      - bidsschematools==0.7.2
      - bleach==6.1.0
      - botocore==1.34.51
      - certifi==2024.2.2
      - cffi==1.16.0
      - charset-normalizer==3.3.2
      - ci-info==0.3.0
      - click==8.1.7
      - click-didyoumean==0.3.0
      - colorama==0.4.6
      - comm==0.2.1
      - contourpy==1.2.0
      - cycler==0.12.1
      - dandi==0.60.0
      - dandischema==0.10.0
      - debugpy==1.8.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dnspython==2.6.1
      - email-validator==2.1.1
      - etelemetry==0.3.1
      - executing==2.0.1
      - fasteners==0.19
      - fastjsonschema==2.19.1
      - fonttools==4.49.0
      - fqdn==1.5.1
      - frozenlist==1.4.1
      - fscacher==0.4.0
      - fsspec==2024.2.0
      - future==1.0.0
      - h11==0.14.0
      - h5py==3.10.0
      - hdmf==3.12.2
      - httpcore==1.0.3
      - httpx==0.26.0
      - humanize==4.9.0
      - idna==3.6
      - importlib-metadata==7.0.1
      - interleave==0.2.1
      - ipykernel==6.29.2
      - ipython==8.21.0
      - ipywidgets==8.1.2
      - isodate==0.6.1
      - isoduration==20.11.0
      - jaraco-classes==3.3.1
      - jedi==0.19.1
      - jinja2==3.1.3
      - jmespath==1.0.1
      - joblib==1.3.2
      - json5==0.9.14
      - jsonpointer==2.4
      - jsonschema==4.21.1
      - jsonschema-specifications==2023.12.1
      - jupyter-client==8.6.0
      - jupyter-core==5.7.1
      - jupyter-events==0.9.0
      - jupyter-lsp==2.2.2
      - jupyter-server==2.12.5
      - jupyter-server-terminals==0.5.2
      - jupyterlab==4.1.1
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.25.3
      - jupyterlab-widgets==3.0.10
      - keyring==24.3.1
      - keyrings-alt==5.0.0
      - kiwisolver==1.4.5
      - markupsafe==2.1.5
      - matplotlib==3.8.3
      - matplotlib-inline==0.1.6
      - mistune==3.0.2
      - more-itertools==10.2.0
      - multidict==6.0.5
      - natsort==8.4.0
      - nbclient==0.9.0
      - nbconvert==7.16.1
      - nbformat==5.9.2
      - nest-asyncio==1.6.0
      - notebook==7.1.0
      - notebook-shim==0.2.4
      - numcodecs==0.12.1
      - numpy==1.26.4
      - nwbinspector==0.4.33
      - opencv-python-headless==4.9.0.80
      - overrides==7.7.0
      - packaging==23.2
      - pandas==2.2.1
      - pandocfilters==1.5.1
      - parso==0.8.3
      - pillow==10.2.0
      - platformdirs==4.2.0
      - prometheus-client==0.20.0
      - prompt-toolkit==3.0.43
      - psutil==5.9.8
      - pure-eval==0.2.2
      - pycparser==2.21
      - pycryptodomex==3.20.0
      - pydantic==2.6.3
      - pydantic-core==2.16.3
      - pygments==2.17.2
      - pynwb==2.6.0.post0.dev15
      - pyout==0.7.3
      - pyparsing==3.1.1
      - python-dateutil==2.8.2
      - python-json-logger==2.0.7
      - pytz==2024.1
      - pywin32==306
      - pywin32-ctypes==0.2.2
      - pywinpty==2.0.12
      - pyyaml==6.0.1
      - pyzmq==25.1.2
      - referencing==0.33.0
      - remfile==0.1.10
      - requests==2.31.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987==1.3.8
      - rpds-py==0.18.0
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - s3fs==2024.2.0
      - scipy==1.12.0
      - semantic-version==2.10.0
      - send2trash==1.8.2
      - six==1.16.0
      - sniffio==1.3.0
      - soupsieve==2.5
      - stack-data==0.6.3
      - tenacity==8.2.3
      - terminado==0.18.0
      - tinycss2==1.2.1
      - tornado==6.4
      - tqdm==4.66.2
      - traitlets==5.14.1
      - types-python-dateutil==2.8.19.20240106
      - typing-extensions==4.10.0
      - tzdata==2024.1
      - uri-template==1.3.0
      - urllib3==2.0.7
      - wcwidth==0.2.13
      - webcolors==1.13
      - webencodings==0.5.1
      - websocket-client==1.7.0
      - widgetsnbextension==4.0.10
      - wrapt==1.16.0
      - yarl==1.9.4
      - zarr==2.17.0
      - zarr-checksum==0.4.0
      - zipp==3.17.0
